// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'basic-title'
  | 'disableForLanguages'
  | 'disableForLanguagesInput'
  | 'enableBionicReader'
  | 'enableReaderToolbarButton'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menu-enableBionic'
  | 'menu-enableBionicForCurrentItem'
  | 'menu-refreshReaders'
  | 'opacityContrast'
  | 'parsing-title'
  | 'parsingOffset'
  | 'parsingPreviewWarning'
  | 'pref-help'
  | 'weightContrast'
  | 'weightOffset';
